// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvb-LyhXDqXY9nOvyf7ipFEbQMhYsTpY',
    appId: '1:865288888233:web:b6a858a6a9dda8e3eb6eb8',
    messagingSenderId: '865288888233',
    projectId: 'frwk-c5ffd',
    authDomain: 'frwk-c5ffd.firebaseapp.com',
    storageBucket: 'frwk-c5ffd.appspot.com',
    measurementId: 'G-M0JEFFZK35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qR4j57vOXH8H0sj53F2w9I5x6za6u_Q',
    appId: '1:865288888233:android:2c058a5056410aa3eb6eb8',
    messagingSenderId: '865288888233',
    projectId: 'frwk-c5ffd',
    storageBucket: 'frwk-c5ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwYvWAats7eJNjaoQfvVENmFo5jH7s0M',
    appId: '1:865288888233:ios:ffed696d6c26f532eb6eb8',
    messagingSenderId: '865288888233',
    projectId: 'frwk-c5ffd',
    storageBucket: 'frwk-c5ffd.appspot.com',
    iosClientId: '865288888233-ej361jamt9fkko555jp6m7ujkbkllu01.apps.googleusercontent.com',
    iosBundleId: 'br.com.frwk.ecomm',
  );
}
